import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import BottomBar from "@/components/shared/Bottombar";
import TopBar from "@/components/shared/Tobar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-screen-2xl m-auto`}>
        <TopBar />

        <main className="flex flex-row">
          <section className="apply flex min-h-screen flex-1 flex-col items-center bg-dark-1 px-6 pb-10 pt-28 max-md:pb-32 sm:px-10">
            <div className="w-full max-w-4xl">{children}</div>
          </section>
        </main>

        <BottomBar />
      </body>
    </html>
  );
}
