import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import TopBar from "@/components/shared/appTopBar";
import Authorization from "./(auth)";
import BottomBar from "@/components/shared/appBottomBar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Provider from "@/utils/Provider";
import Loading from "@/utils/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${inter.className} container h-screen max-h-[-webkit-fill-available] overflow-auto m-auto`}
        >
          <Loading>
            <main className="w-full">
              <TopBar />
              <section className="apply flex  flex-1 flex-col items-center bg-dark-1 px-6 pb-8 pt-2 max-md:pb-32 sm:px-10">
                <div className="w-full overflow-auto ">
                  <ToastContainer
                    position="bottom-left"
                    autoClose={5000}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                  />
                  {children}
                </div>
              </section>
              <BottomBar />
            </main>
            <Authorization />
          </Loading>
        </body>
      </Provider>
    </html>
  );
}
